export default function loadMenu(){
    const content= document.querySelector("#content");
    const menu = document.createElement('div');
    content.appendChild(menu);
    menu.id='menu';
    const heading= document.createElement("p");
    menu.appendChild(heading);
    heading.textContent="We've Got :";
    heading.id='heading';
    const appetizers = document.createElement('div');
    appetizers.id='appetizers';
    menu.appendChild(appetizers);
    appetizers.textContent='Appetizers';
    const item1 = document.createElement('p');
    item1.id='item1';
    item1.textContent='- Gotham Harbor Oysters';
    const item2 = document.createElement('p');
    item2.id='item2';
    item2.textContent="- Penguin's Imperial Caviar";
    const item3 = document.createElement('p');
    item3.id='item3';
    item3.textContent='- Arctic Shrimp Cocktail';
    const item4 = document.createElement('p');
    item4.id='item4';
    item4.textContent='- Truffle Tune Tartare';
    appetizers.appendChild(item1);
    appetizers.appendChild(item2);
    appetizers.appendChild(item3);
    appetizers.appendChild(item4);
    const mainCourses = document.createElement('div');
    mainCourses.id='mainCourses';
    menu.appendChild(mainCourses);
    mainCourses.textContent='Main Courses';
    const item5 = document.createElement('p');
    item5.id='item5';
    item5.textContent='- Glacial Salmon Sashimi';
    const item6 = document.createElement('p');
    item6.id='item6';
    item6.textContent="- Frostbite Ramen";
    const item7 = document.createElement('p');
    item7.id='item7';
    item7.textContent='- Snowy Mountain Udon';
    const item8 = document.createElement('p');
    item8.id='item8';
    item8.textContent='- Iceberg Tempura Platter';
    mainCourses.appendChild(item5);
    mainCourses.appendChild(item6);
    mainCourses.appendChild(item7);
    mainCourses.appendChild(item8);
    const item9 = document.createElement('p');
    item9.id='item9';
    item9.textContent='- Roasted Duck à la Cobblepot';
    const desserts = document.createElement('div');
    desserts.id='desserts';
    menu.appendChild(desserts);
    desserts.textContent='Desserts';
    const item10 = document.createElement('p');
    item10.id='item10';
    item10.textContent='- Frozen Delight Parfait';
    desserts.appendChild(item10);
    const item11 = document.createElement('p');
    item11.id='item11';
    item11.textContent="- Arctic Chocolate Mousse";
    desserts.appendChild(item11);
    const item12 = document.createElement('p');
    item12.id='item12';
    item12.textContent='- Black & White Tuxedo Cake';
    desserts.appendChild(item12);
    const signature= document.createElement('div');
    menu.appendChild(signature);
    signature.textContent="Signature Cocktails";
    signature.id='signature';
    const item13= document.createElement('p');
    item13.id='item13';
    item13.textContent='- The Cobblepot Martini';
    signature.appendChild(item13);
    const item14= document.createElement('p');
    item14.id='item14';
    item14.textContent='- Blackgate Old Fashioned';
    signature.appendChild(item14);
    const item15= document.createElement('p');
    item15.id='item15';
    item15.textContent='- The Iceberg Royale';
    signature.appendChild(item15);
    const item16= document.createElement('p');
    item16.id='item16';
    item16.textContent="- Penguin's Reserve Champagne";
    signature.appendChild(item16);
    const dialogue = document.createElement('div');
    dialogue.id='dialogue';
    dialogue.textContent='Like we said, Finest!';
    menu.appendChild(dialogue);
}